set nocompatible
set ruler
set autochdir
set directory=/tmp
set colorcolumn=81

syntax on
set background=dark

if has('unix')
  let s:uname = system('uname')
  if s:uname == "Darwin\n"
    " OSX-specific options
    colorscheme solarized
    set guifont=SourceCodePro-Regular:h11
  else
    set guifont=SourceCodePro
  endif
endif

if has('gui_running')
  colorscheme solarized


  set cursorline

  " hide toolbar
  :set guioptions-=T

  " make ctrl+c and ctrl+v copy and paste
  nmap <C-S-V> "+gP
  imap <C-S-V> <ESC><C-S-V>i
  vmap <C-S-C> "+y
endif

autocmd FileType * set tabstop=4|set shiftwidth=4
autocmd FileType sh,perl,awk,python set tabstop=4|set shiftwidth=4|set expandtab|set smartindent
autocmd FileType ruby set tabstop=2|set shiftwidth=2|set expandtab|set smartindent
autocmd FileType c,h,cpp set tabstop=8|set shiftwidth=8|set noexpandtab|set cindent
autocmd FileType make set tabstop=8|set shiftwidth=8|set noexpandtab
autocmd FileType asm set tabstop=8|set shiftwidth=8|set noexpandtab
