# if not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# set history length
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

export CLICOLOR=1
export EDITOR=vim
export UBUNTU_MENUPROXY=
export HOMEBREW_PREFIX=$(brew --prefix)
export GITHUB_USER="mlafeldt"

# enable bash completion
[ -f /etc/bash_completion ] && . /etc/bash_completion
if command -v brew >/dev/null; then
    [ -f "$(brew --prefix)/etc/bash_completion" ] && . "$(brew --prefix)/etc/bash_completion"
fi

# chruby setup
if [ -d "$HOMEBREW_PREFIX/opt/chruby" ]; then
    . "$HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh"
    . "$HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh"
fi

# pythonbrew setup
[ -s "$HOME/.pythonbrew/etc/bashrc" ] && . "$HOME/.pythonbrew/etc/bashrc"

# set prompt
PS1="[\W]\$ "

# set git prompt if installed
if command -v git >/dev/null; then
    [ -f "$HOME/.git-prompt.sh" ] && . "$HOME/.git-prompt.sh"
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1='[\W$(__git_ps1 " (%s)")]\$ '
    PS1="$GIT_PS1"
fi

# include alias definitions
[ -f "$HOME/.bash_aliases" ] && . "$HOME/.bash_aliases"

# source local settings if present
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"

:
