# vim: ft=sh

alias ag=rg
alias rga='rg --no-ignore'
alias cat=bat
alias hd='hexdump -C'

alias zb='zig build --summary new'
alias zt='zig build test --summary new'
alias zc='zig build check --summary new'

alias python=python3
alias pip=pip3

alias dyl='dy --region local --port 8000'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias t='tree --gitignore'
alias ta='tree -a'
alias ts='tree -ash --du'

complete -o default -F __start_kubectl kc
alias kn=kubens;  complete -F _kube_namespaces kn
alias kx=kubectx; complete -F _kube_contexts kx
alias kw='watch "kubectl get pods -A | grep -vE \"(Completed|Running)\""'

alias ubuntu='docker run -it --rm -v $(PWD):/data -w /data ubuntu /bin/bash'
alias centos='docker run -it --rm -v $(PWD):/data -w /data centos /bin/bash'
alias alpine='docker run -it --rm -v $(PWD):/data -w /data alpine /bin/sh'

alias fix-spotlight='sudo mdutil -i on /'
alias fix-dns='sudo killall -HUP mDNSResponder'

# fat fingers...
alias gti=git
alias got=go
alias bim=vim

alias claude="$HOME/.claude/local/claude"
alias claude-yolo="claude --dangerously-skip-permissions"

:
